Added date to Signup form. Now it is possible to register new accounts.
ishLearn/ishLearn pull request #137
Opened 2022-06-22 20:07 UTC by Johann-jpg

2022-06-22 20:28 UTC, SebastianThomas requested changes
Okay but type checking required, see comment

2022-06-22 20:28 UTC, SebastianThomas commented on ishlearn-client/src/services/auth.service.ts
> +    birthday: string
Wieso `string` und nicht `Date`? Funktioniert so auch der Signup?

2022-06-22 21:28 UTC, Johann-jpg commented on ishlearn-client/src/services/auth.service.ts
> +    birthday: string
ich habe new Date(birthday) ausprobiert, die Konvertierung hat geklappt, aber die Datenbank hat sich über das Fromat beschwert. Da habe ich das als String gemacht und es kam keine Beschwerde. 
Ich habe bisher keine genauere User View implementiert bzw. weiß ich gar nicht, ob du mir das Datum schickst, um es zu kontrollieren.

2022-06-23 07:40 UTC, SebastianThomas commented on ishlearn-client/src/services/auth.service.ts
> +    birthday: string
![image](https://user-images.githubusercontent.com/54369369/175243687-0b0a09bd-658a-466f-ab76-353772bf0c79.png)
Okay, dann baue ich validation im Backend, oder funktioniert das schon?

2022-06-23 10:53 UTC, merged